# Dependencies
markdown:         redcarpet
highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Jacob N. Oppenheim'
tagline:          'PhD'
description:      'description'
url:              #http://jnoppenheim.github.io

author:
  name:           'Jaocb Oppenheim'
  url:            #https://jnoppenheim.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/jnoppenheim/jnoppenheim.github.io

#banner: "/quasicrystal_tile.jpg"