# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Jacob N. Oppenheim'
tagline:          'PhD'
description:      'description'
url:              http://jacobo.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

banner: "/quasicrystal_tile.jpg"